{
  "name": "/client-api/v2/bill-pay/payments/{id}_GET",
  "request": {
    "url": "/client-api/v2/bill-pay/payments/[^/]+(\\?.*)?$",
    "method": "GET"
  },
  "responses": {
    "success": {
      "status": 200,
      "data": {
        "payment": {
          "id": "8a9483495f058d2f015f058d366a003c",
          "payeeID": "0002",
          "payeeName": "Citibank",
          "payeeAccountNumber": "100000001",
          "payeeElectronic": false,
          "amount": {
            "amount": "100.99",
            "currencyCode": "USD"
          },
          "paymentDate": "2019-02-22",
          "paymentAccount": {
            "id": "1",
            "accountNumber": "000000001",
            "routingNumber": "000000011",
            "accountType": "CHECKING_ACCOUNT"
          },
          "recurring": false,
          "automaticPayment": false,
          "status": "PENDING",
          "fee": {
            "amount": "9.99",
            "currencyCode": "USD"
          },
          "ebillID": "20141219140239655590"
        }
      },
      "default": true
    },
    "badRequest": {
      "status": 400,
      "data": {
        "message": "Bad Request",
        "key": "GENERAL_ERROR",
        "errors": [
          {
            "message": "Value Exceeded. Must be between {min} and {max}.",
            "key": "common.api.shoesize",
            "context": {
              "max": "50",
              "min": "1"
            }
          }
        ]
      }
    },
    "notFound": {
      "status": 404,
      "data": {
        "message": "Resource not found.",
        "key": "GENERAL_ERROR",
        "errors": [
          {
            "message": "Unable to find the resource requested resource: {resource}.",
            "key": "common.api.resource",
            "context": {
              "resource": "aResource"
            }
          }
        ]
      }
    },
    "systemError": {
      "status": 500,
      "data": {
        "message": "Description of error"
      }
    },
    "notSupported": {
      "status": 501,
      "data": {
        "message": "Operation not supported"
      }
    },
    "badGateway": {
      "status": 502,
      "data": {
        "message": "Bad Gateway",
        "key": "GENERAL_ERROR",
        "errors": [
          {
            "message": "Internal error calling API provider",
            "key": "common.api.providerInternalError"
          }
        ]
      }
    },
    "gatewayTimeout": {
      "status": 504,
      "data": {
        "message": "Gateway Timeout",
        "key": "GENERAL_ERROR",
        "errors": [
          {
            "message": "API provider unavailable.",
            "key": "common.api.providerUnavailable"
          }
        ]
      }
    }
  }
}
